import type { Metadata } from "next";
import localFont from "next/font/local";
import { ThemeModeScript } from "flowbite-react";
import "./globals.css";
import Providers from "./providers";

const helvetica = localFont({
  src: [
    {
      path: '../public/fonts/helvetica_neue_lt_std_43_light.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/fonts/helvetica_neue_lt_std_73_bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-helvetica',
});

export const metadata: Metadata = {
  title: "Mateo Suarez",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
        <link rel="stylesheet" type='text/css' href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css" />
      </head>
      <body className={`${helvetica.variable} antialiased`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
