import type { Metadata } from "next";
import { ThemeModeScript } from "flowbite-react";
import "./globals.css";
import Providers from "./providers";
import { Work_Sans } from "next/font/google";

const workSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-work-sans",
  weight: ["300", "400", "500", "600", "700", "800"],
  display: "swap",
}); 

export const metadata: Metadata = {
  title: "Mateo Suarez - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
        <link rel="stylesheet" type='text/css' href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/
        devicon.min.css" />
      </head>
      <body className={`antialiased ${workSans.className}`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
